api:
  version:  v2

server:
  port:     8090

database:
  type:     postgres1
  host:     localhost1
  port:     5431
  user:     postgres1
  password: secret1
  name:     xmex

redis:
  host:     127.0.0.1
  port:     6378

jwt:
  secret: sedfqeSDFasfADSFASdfqe44FASFw4RRRW